### ISSUE TITLE
Unable to pick which midi device to load settings from

### ISSUE THREAD

**Issue by dyc3** [abridgewater/alesisvsysex#12]
Steps:
1. Plug in an Aleis VI49
2. 2 MIDI devices should show up with `amidi -l`
```
Dir Device    Name
IO  hw:3,0,0  VI49 MIDI 1
IO  hw:3,0,1  VI49 MIDI 2
```
3. Open the application
4. Click load from device
5. See that the app crashes

Output:
```
Traceback (most recent call last):
  File "/home/carson/Documents/code/other/alesisvsysex/alesisvsysex/ui/window.py", line 175, in loadDevice
    device = self.findMIDIDevice(True)
  File "/home/carson/Documents/code/other/alesisvsysex/alesisvsysex/ui/window.py", line 163, in findMIDIDevice
    raise RuntimeError("Multiple compatible MIDI devices found")
RuntimeError: Multiple compatible MIDI devices found
[1]    767967 abort (core dumped)  python3 -m alesisvsysex
```

**Comment by dyc3** [comment]
For some reason, it sees both usb devices as `VI49 MIDI 2`, and `VI49 MIDI 1` does not appear. That's probably a different bug.
